### ISSUE TITLE
Sidekiq 8.0.3 breaks Resque integration tests

### ISSUE THREAD

**Issue by Mangara** [Shopify/job-iteration#575]
After bumping Sidekiq to v8.0.3, the Resque integration tests fail with

```
NoMethodError: undefined method 'config' for nil (NoMethodError)

      if Rails.application.config.eager_load
                          ^^^^^^^
/Users/sander/.gem/ruby/3.4.2/gems/resque-2.7.0/lib/resque/tasks.rb:46:in 'block (2 levels) in <top (required)>'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli/exec.rb:59:in 'Kernel.load'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli.rb:452:in 'Bundler::CLI#exec'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/exe/bundle:28:in 'block in <top (required)>'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
/Users/sander/.gem/ruby/3.4.2/gems/bundler-2.6.1/exe/bundle:20:in '<top (required)>'
/Users/sander/.gem/ruby/3.4.2/bin/bundle:25:in 'Kernel#load'
/Users/sander/.gem/ruby/3.4.2/bin/bundle:25:in '<main>'
Tasks: TOP => resque:work => resque:preload
```

It has something to do with https://github.com/sidekiq/sidekiq/pull/6669 and https://github.com/sidekiq/sidekiq/issues/6683, but I'm not sure if Sidekiq is doing something wrong, or if Resque's expectations are incorrect, or if the way we're using them in these tests breaks the expectations of a normal Rails app.

**Comment by Mangara** [comment]
This has been fixed in Sidekiq.
